In [49]:
import numpy as np
import  pandas as pd
from sklearn.metrics import f1_score
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2,f_classif

In [50]:
cd=pd.read_csv("telecom.csv")
cdf=pd.DataFrame(cd)
print(cdf.info())
print(cdf.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
customerID          7043 non-null object
gender              7043 non-null object
SeniorCitizen       7043 non-null int64
Partner             7043 non-null object
Dependents          7043 non-null object
tenure              7043 non-null int64
PhoneService        7043 non-null object
MultipleLines       7043 non-null object
InternetService     7043 non-null object
OnlineSecurity      7043 non-null object
OnlineBackup        7043 non-null object
DeviceProtection    7043 non-null object
TechSupport         7043 non-null object
StreamingTV         7043 non-null object
StreamingMovies     7043 non-null object
Contract            7043 non-null object
PaperlessBilling    7043 non-null object
PaymentMethod       7043 non-null object
MonthlyCharges      7043 non-null float64
TotalCharges        7043 non-null object
Churn               7043 non-null object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB
None
       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [51]:
list1 = [ 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
                'TechSupport','StreamingTV', 'StreamingMovies']
for i in list1:
    cdf[i] = cdf[i].replace({'No internet service':'No'})
cdf['MultipleLines'] = cdf['MultipleLines'].replace({'No phone service':'No'})
cdf.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [52]:
list2=[ 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection','Churn',
                'TechSupport','StreamingTV', 'StreamingMovies','MultipleLines','Partner','Dependents','PaperlessBilling','PhoneService']
for i in list2:
    cdf[i]= cdf[i].replace({'Yes':1,'No':0})
print(cdf.head())

   customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
0  7590-VHVEG  Female              0        1           0       1
1  5575-GNVDE    Male              0        0           0      34
2  3668-QPYBK    Male              0        0           0       2
3  7795-CFOCW    Male              0        0           0      45
4  9237-HQITU  Female              0        0           0       2

   PhoneService  MultipleLines InternetService  OnlineSecurity  ...  \
0             0              0             DSL               0  ...
1             1              0             DSL               1  ...
2             1              0             DSL               1  ...
3             0              0             DSL               1  ...
4             1              0     Fiber optic               0  ...

   DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
0                 0            0            0                0
1                 1            0            0                0
2                 0            0            0                0
3                 1            1            0                0
4                 0            0            0                0

         Contract PaperlessBilling              PaymentMethod MonthlyCharges  \
0  Month-to-month                1           Electronic check          29.85
1        One year                0               Mailed check          56.95
2  Month-to-month                1               Mailed check          53.85
3        One year                0  Bank transfer (automatic)          42.30
4  Month-to-month                1           Electronic check          70.70

   TotalCharges Churn
0         29.85     0
1        1889.5     0
2        108.15     1
3       1840.75     0
4        151.65     1

[5 rows x 21 columns]

In [53]:
gen=pd.get_dummies(cdf["gender"],drop_first = True)
cdf=pd.concat((cdf,gen),axis=1)
cdf.drop(['gender'],axis=1,inplace=True)
y=pd.get_dummies(cdf["InternetService"])
y.drop(['No'],axis=1,inplace=True)
cdf.drop(['InternetService'],axis=1,inplace=True)
cdf=pd.concat((cdf,y),axis=1)
x=pd.get_dummies(cdf["Contract"])
cdf.drop(["Contract"],axis=1,inplace=True)
cdf=pd.concat((cdf,x),axis=1)
cdf.drop(["PaymentMethod"],axis=1,inplace=True)
cdf.drop(["customerID"],axis=1,inplace=True)
cdf['tenure']=cdf['tenure'].replace({0:0.1})

print(cdf.head())

   SeniorCitizen  Partner  Dependents  tenure  PhoneService  MultipleLines  \
0              0        1           0     1.0             0              0
1              0        0           0    34.0             1              0
2              0        0           0     2.0             1              0
3              0        0           0    45.0             0              0
4              0        0           0     2.0             1              0

   OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  ...  \
0               0             1                 0            0  ...
1               1             0                 1            0  ...
2               1             1                 0            0  ...
3               1             0                 1            1  ...
4               0             0                 0            0  ...

   PaperlessBilling  MonthlyCharges  TotalCharges  Churn Male  DSL  \
0                 1           29.85         29.85      0    0    1
1                 0           56.95        1889.5      0    1    1
2                 1           53.85        108.15      1    1    1
3                 0           42.30       1840.75      0    1    1
4                 1           70.70        151.65      1    0    0

   Fiber optic  Month-to-month  One year  Two year
0            0               1         0         0
1            0               0         1         0
2            0               1         0         0
3            0               0         1         0
4            1               1         0         0

[5 rows x 22 columns]

In [54]:
ten=np.log(cdf['tenure'])
cdf.drop(["tenure"],axis=1,inplace=True)
cdf=pd.concat((cdf,ten),axis=1)
cdf['TotalCharges'] =pd.to_numeric(cdf['TotalCharges'], errors ='coerce')
z=cdf.dropna()
index =cdf['TotalCharges'].index[cdf['TotalCharges'].apply(np.isnan)]
c=[]
c.extend(index)
# values of the monthlycharges corresponding to which the values of totalcharges is null or nan!
d=cdf.loc[c,["MonthlyCharges"]]
x= z["MonthlyCharges"].values
m=len(x)
x=x.reshape((m,-1))
y= z["TotalCharges"].values
y = y.reshape((m,-1))
regmodel=linear_model.LinearRegression()
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.3,random_state=42)
regmodel.fit(x_train,y_train)
a= regmodel.predict(d)
list1=[]
for i in a:
    list1.extend(i)
r2= regmodel.score(x,y)
print("Accuracy of linear model used for predicting a null values of TotalCharges in the data set : ", r2)
for i in list1:
    cdf['TotalCharges']=(cdf['TotalCharges'].fillna(i,limit= 1))
tc=np.log(cdf['TotalCharges'])
cdf.drop(['TotalCharges'],axis=1,inplace=True)
cdf=pd.concat((cdf,tc),axis=1)
mc=np.log(cdf['MonthlyCharges'])
cdf.drop(['MonthlyCharges'],axis=1,inplace=True)
cdf=pd.concat((cdf,mc),axis=1)
# Changing all negative values into non-negative values:
cdf=cdf.abs()
print(cdf.describe())
cdf.head()

Accuracy of linear model used for predicting a null values of TotalCharges in the data set :  0.4238558780398537
       SeniorCitizen      Partner   Dependents  PhoneService  MultipleLines  \
count    7043.000000  7043.000000  7043.000000   7043.000000    7043.000000
mean        0.162147     0.483033     0.299588      0.903166       0.421837
std         0.368612     0.499748     0.458110      0.295752       0.493888
min         0.000000     0.000000     0.000000      0.000000       0.000000
25%         0.000000     0.000000     0.000000      1.000000       0.000000
50%         0.000000     0.000000     0.000000      1.000000       0.000000
75%         0.000000     1.000000     1.000000      1.000000       1.000000
max         1.000000     1.000000     1.000000      1.000000       1.000000

       OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  \
count     7043.000000   7043.000000       7043.000000  7043.000000
mean         0.286668      0.344881          0.343888     0.290217
std          0.452237      0.475363          0.475038     0.453895
min          0.000000      0.000000          0.000000     0.000000
25%          0.000000      0.000000          0.000000     0.000000
50%          0.000000      0.000000          0.000000     0.000000
75%          1.000000      1.000000          1.000000     1.000000
max          1.000000      1.000000          1.000000     1.000000

       StreamingTV  ...        Churn         Male          DSL  Fiber optic  \
count  7043.000000  ...  7043.000000  7043.000000  7043.000000  7043.000000
mean      0.384353  ...     0.265370     0.504756     0.343746     0.439585
std       0.486477  ...     0.441561     0.500013     0.474991     0.496372
min       0.000000  ...     0.000000     0.000000     0.000000     0.000000
25%       0.000000  ...     0.000000     0.000000     0.000000     0.000000
50%       0.000000  ...     0.000000     1.000000     0.000000     0.000000
75%       1.000000  ...     1.000000     1.000000     1.000000     1.000000
max       1.000000  ...     1.000000     1.000000     1.000000     1.000000

       Month-to-month     One year     Two year       tenure  TotalCharges  \
count     7043.000000  7043.000000  7043.000000  7043.000000   7043.000000
mean         0.550192     0.209144     0.240664     2.916909      6.938430
std          0.497510     0.406726     0.427517     1.324141      1.553139
min          0.000000     0.000000     0.000000     0.000000      2.933857
25%          0.000000     0.000000     0.000000     2.197225      5.991839
50%          1.000000     0.000000     0.000000     3.367296      7.242297
75%          1.000000     0.000000     0.000000     4.007333      8.239224
max          1.000000     1.000000     1.000000     4.276666      9.069330

       MonthlyCharges
count     7043.000000
mean         4.021917
std          0.594424
min          2.904165
25%          3.569533
50%          4.253483
75%          4.498142
max          4.777020

[8 rows x 22 columns]

,SeniorCitizen,Partner,Dependents,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,...,Churn,Male,DSL,Fiber optic,Month-to-month,One year,Two year,tenure,TotalCharges,MonthlyCharges
0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.000000,3.396185,3.396185
1,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,3.526361,7.544068,4.042174
2,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.693147,4.683519,3.986202
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,1.0,1.0,0.0,0.0,1.0,0.0,3.806662,7.517928,3.744787
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.693147,5.021575,4.258446

In [59]:
print(cdf.tail())

      SeniorCitizen  Partner  Dependents  PhoneService  MultipleLines  \
7038            0.0      1.0         1.0           1.0            1.0
7039            0.0      1.0         1.0           1.0            1.0
7040            0.0      1.0         1.0           0.0            0.0
7041            1.0      1.0         0.0           1.0            1.0
7042            0.0      0.0         0.0           1.0            0.0

      OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  \
7038             1.0           0.0               1.0          1.0
7039             0.0           1.0               1.0          0.0
7040             1.0           0.0               0.0          0.0
7041             0.0           0.0               0.0          0.0
7042             1.0           0.0               1.0          1.0

      StreamingTV  ...  Churn  Male  DSL  Fiber optic  Month-to-month  \
7038          1.0  ...    0.0   1.0  1.0          0.0             0.0
7039          1.0  ...    0.0   0.0  0.0          1.0             0.0
7040          0.0  ...    0.0   0.0  1.0          0.0             1.0
7041          0.0  ...    1.0   1.0  0.0          1.0             1.0
7042          1.0  ...    0.0   1.0  0.0          1.0             0.0

      One year  Two year    tenure  TotalCharges  MonthlyCharges
7038       1.0       0.0  3.178054      7.596141        4.440296
7039       1.0       0.0  4.276666      8.904209        4.636669
7040       0.0       0.0  2.397895      5.847739        3.387774
7041       0.0       0.0  1.386294      5.725544        4.309456
7042       0.0       1.0  4.189655      8.831201        4.660132

[5 rows x 22 columns]